
from SCons.Script import Import

Import('env')

env.Require('gitinfo')

# Since this is often a submodule, use the git version info for the
# submodule.
env.LoadGitInfo('.')

version = env.get('REPO_REVISION', 'unknown')
if version == 'unknown' or env.get('REPO_ERROR'):
    version = None

# If git revision info is loaded successfully, then set the
# auto-revision, otherwise the default will be used.
if version:
    env.Append(CPPDEFINES=['BSPLINE_AUTO_REVISION="%s"' % (version)])

sources = ['BSplineLib.cpp']

bsplinelib = env.Library('bspline', sources)

env.Default(bsplinelib)
