
tools = ['default',]
env = Environment(tools = tools)
env.AppendUnique(CPPPATH='#/BSpline')
env.AppendUnique(LIBPATH=['#/BSpline/BSpline', ])
env.AppendUnique(LIBS=['bspline',])

sources = Split('''
driver.cpp
''')

driver = env.Program('driver', sources)

env.Default(driver)
